//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WpfClientApp.WebAnimalTestService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebAnimalServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebAnimalService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMammalOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddAtriOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddBirdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAnimalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMammalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArtiOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBirdsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveAnimalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveMammalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveArtiOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveBirdsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebAnimalService() {
            this.Url = global::WpfClientApp.Properties.Settings.Default.WpfClientApp_WebAnimalTestService_WebAnimalService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event AddAnimalCompletedEventHandler AddAnimalCompleted;
        
        /// <remarks/>
        public event AddMammalCompletedEventHandler AddMammalCompleted;
        
        /// <remarks/>
        public event AddAtriCompletedEventHandler AddAtriCompleted;
        
        /// <remarks/>
        public event AddBirdCompletedEventHandler AddBirdCompleted;
        
        /// <remarks/>
        public event GetAnimalsCompletedEventHandler GetAnimalsCompleted;
        
        /// <remarks/>
        public event GetMammalsCompletedEventHandler GetMammalsCompleted;
        
        /// <remarks/>
        public event GetArtiCompletedEventHandler GetArtiCompleted;
        
        /// <remarks/>
        public event GetBirdsCompletedEventHandler GetBirdsCompleted;
        
        /// <remarks/>
        public event RemoveAnimalsCompletedEventHandler RemoveAnimalsCompleted;
        
        /// <remarks/>
        public event RemoveMammalsCompletedEventHandler RemoveMammalsCompleted;
        
        /// <remarks/>
        public event RemoveArtiCompletedEventHandler RemoveArtiCompleted;
        
        /// <remarks/>
        public event RemoveBirdsCompletedEventHandler RemoveBirdsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddAnimal(string name, int age, double weight) {
            object[] results = this.Invoke("AddAnimal", new object[] {
                        name,
                        age,
                        weight});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAnimalAsync(string name, int age, double weight) {
            this.AddAnimalAsync(name, age, weight, null);
        }
        
        /// <remarks/>
        public void AddAnimalAsync(string name, int age, double weight, object userState) {
            if ((this.AddAnimalOperationCompleted == null)) {
                this.AddAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAnimalOperationCompleted);
            }
            this.InvokeAsync("AddAnimal", new object[] {
                        name,
                        age,
                        weight}, this.AddAnimalOperationCompleted, userState);
        }
        
        private void OnAddAnimalOperationCompleted(object arg) {
            if ((this.AddAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAnimalCompleted(this, new AddAnimalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMammal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddMammal(string name, double temp, bool isIswimming) {
            object[] results = this.Invoke("AddMammal", new object[] {
                        name,
                        temp,
                        isIswimming});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddMammalAsync(string name, double temp, bool isIswimming) {
            this.AddMammalAsync(name, temp, isIswimming, null);
        }
        
        /// <remarks/>
        public void AddMammalAsync(string name, double temp, bool isIswimming, object userState) {
            if ((this.AddMammalOperationCompleted == null)) {
                this.AddMammalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMammalOperationCompleted);
            }
            this.InvokeAsync("AddMammal", new object[] {
                        name,
                        temp,
                        isIswimming}, this.AddMammalOperationCompleted, userState);
        }
        
        private void OnAddMammalOperationCompleted(object arg) {
            if ((this.AddMammalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMammalCompleted(this, new AddMammalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAtri", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddAtri(string name, int h_count, bool isRum) {
            object[] results = this.Invoke("AddAtri", new object[] {
                        name,
                        h_count,
                        isRum});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAtriAsync(string name, int h_count, bool isRum) {
            this.AddAtriAsync(name, h_count, isRum, null);
        }
        
        /// <remarks/>
        public void AddAtriAsync(string name, int h_count, bool isRum, object userState) {
            if ((this.AddAtriOperationCompleted == null)) {
                this.AddAtriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAtriOperationCompleted);
            }
            this.InvokeAsync("AddAtri", new object[] {
                        name,
                        h_count,
                        isRum}, this.AddAtriOperationCompleted, userState);
        }
        
        private void OnAddAtriOperationCompleted(object arg) {
            if ((this.AddAtriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAtriCompleted(this, new AddAtriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddBird", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddBird(string name, Color wings, bool isTalking) {
            object[] results = this.Invoke("AddBird", new object[] {
                        name,
                        wings,
                        isTalking});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddBirdAsync(string name, Color wings, bool isTalking) {
            this.AddBirdAsync(name, wings, isTalking, null);
        }
        
        /// <remarks/>
        public void AddBirdAsync(string name, Color wings, bool isTalking, object userState) {
            if ((this.AddBirdOperationCompleted == null)) {
                this.AddBirdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBirdOperationCompleted);
            }
            this.InvokeAsync("AddBird", new object[] {
                        name,
                        wings,
                        isTalking}, this.AddBirdOperationCompleted, userState);
        }
        
        private void OnAddBirdOperationCompleted(object arg) {
            if ((this.AddBirdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBirdCompleted(this, new AddBirdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAnimals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Animal[] GetAnimals() {
            object[] results = this.Invoke("GetAnimals", new object[0]);
            return ((Animal[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAnimalsAsync() {
            this.GetAnimalsAsync(null);
        }
        
        /// <remarks/>
        public void GetAnimalsAsync(object userState) {
            if ((this.GetAnimalsOperationCompleted == null)) {
                this.GetAnimalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAnimalsOperationCompleted);
            }
            this.InvokeAsync("GetAnimals", new object[0], this.GetAnimalsOperationCompleted, userState);
        }
        
        private void OnGetAnimalsOperationCompleted(object arg) {
            if ((this.GetAnimalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAnimalsCompleted(this, new GetAnimalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMammals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Mammal[] GetMammals() {
            object[] results = this.Invoke("GetMammals", new object[0]);
            return ((Mammal[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMammalsAsync() {
            this.GetMammalsAsync(null);
        }
        
        /// <remarks/>
        public void GetMammalsAsync(object userState) {
            if ((this.GetMammalsOperationCompleted == null)) {
                this.GetMammalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMammalsOperationCompleted);
            }
            this.InvokeAsync("GetMammals", new object[0], this.GetMammalsOperationCompleted, userState);
        }
        
        private void OnGetMammalsOperationCompleted(object arg) {
            if ((this.GetMammalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMammalsCompleted(this, new GetMammalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetArti", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Artiodactyls[] GetArti() {
            object[] results = this.Invoke("GetArti", new object[0]);
            return ((Artiodactyls[])(results[0]));
        }
        
        /// <remarks/>
        public void GetArtiAsync() {
            this.GetArtiAsync(null);
        }
        
        /// <remarks/>
        public void GetArtiAsync(object userState) {
            if ((this.GetArtiOperationCompleted == null)) {
                this.GetArtiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArtiOperationCompleted);
            }
            this.InvokeAsync("GetArti", new object[0], this.GetArtiOperationCompleted, userState);
        }
        
        private void OnGetArtiOperationCompleted(object arg) {
            if ((this.GetArtiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArtiCompleted(this, new GetArtiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBirds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Bird[] GetBirds() {
            object[] results = this.Invoke("GetBirds", new object[0]);
            return ((Bird[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBirdsAsync() {
            this.GetBirdsAsync(null);
        }
        
        /// <remarks/>
        public void GetBirdsAsync(object userState) {
            if ((this.GetBirdsOperationCompleted == null)) {
                this.GetBirdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBirdsOperationCompleted);
            }
            this.InvokeAsync("GetBirds", new object[0], this.GetBirdsOperationCompleted, userState);
        }
        
        private void OnGetBirdsOperationCompleted(object arg) {
            if ((this.GetBirdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBirdsCompleted(this, new GetBirdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveAnimals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemoveAnimals() {
            object[] results = this.Invoke("RemoveAnimals", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveAnimalsAsync() {
            this.RemoveAnimalsAsync(null);
        }
        
        /// <remarks/>
        public void RemoveAnimalsAsync(object userState) {
            if ((this.RemoveAnimalsOperationCompleted == null)) {
                this.RemoveAnimalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveAnimalsOperationCompleted);
            }
            this.InvokeAsync("RemoveAnimals", new object[0], this.RemoveAnimalsOperationCompleted, userState);
        }
        
        private void OnRemoveAnimalsOperationCompleted(object arg) {
            if ((this.RemoveAnimalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveAnimalsCompleted(this, new RemoveAnimalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveMammals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemoveMammals() {
            object[] results = this.Invoke("RemoveMammals", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveMammalsAsync() {
            this.RemoveMammalsAsync(null);
        }
        
        /// <remarks/>
        public void RemoveMammalsAsync(object userState) {
            if ((this.RemoveMammalsOperationCompleted == null)) {
                this.RemoveMammalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveMammalsOperationCompleted);
            }
            this.InvokeAsync("RemoveMammals", new object[0], this.RemoveMammalsOperationCompleted, userState);
        }
        
        private void OnRemoveMammalsOperationCompleted(object arg) {
            if ((this.RemoveMammalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveMammalsCompleted(this, new RemoveMammalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveArti", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemoveArti() {
            object[] results = this.Invoke("RemoveArti", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveArtiAsync() {
            this.RemoveArtiAsync(null);
        }
        
        /// <remarks/>
        public void RemoveArtiAsync(object userState) {
            if ((this.RemoveArtiOperationCompleted == null)) {
                this.RemoveArtiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveArtiOperationCompleted);
            }
            this.InvokeAsync("RemoveArti", new object[0], this.RemoveArtiOperationCompleted, userState);
        }
        
        private void OnRemoveArtiOperationCompleted(object arg) {
            if ((this.RemoveArtiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveArtiCompleted(this, new RemoveArtiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveBirds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemoveBirds() {
            object[] results = this.Invoke("RemoveBirds", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveBirdsAsync() {
            this.RemoveBirdsAsync(null);
        }
        
        /// <remarks/>
        public void RemoveBirdsAsync(object userState) {
            if ((this.RemoveBirdsOperationCompleted == null)) {
                this.RemoveBirdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveBirdsOperationCompleted);
            }
            this.InvokeAsync("RemoveBirds", new object[0], this.RemoveBirdsOperationCompleted, userState);
        }
        
        private void OnRemoveBirdsOperationCompleted(object arg) {
            if ((this.RemoveBirdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveBirdsCompleted(this, new RemoveBirdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Color {
        
        /// <remarks/>
        Black,
        
        /// <remarks/>
        White,
        
        /// <remarks/>
        Multicolored,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bird))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Mammal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Artiodactyls))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Animal {
        
        private System.Guid idField;
        
        private double weightField;
        
        private string nameField;
        
        private int ageField;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public double Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bird : Animal {
        
        private bool isTalkingField;
        
        private Color wingsField;
        
        private int eggsField;
        
        /// <remarks/>
        public bool IsTalking {
            get {
                return this.isTalkingField;
            }
            set {
                this.isTalkingField = value;
            }
        }
        
        /// <remarks/>
        public Color Wings {
            get {
                return this.wingsField;
            }
            set {
                this.wingsField = value;
            }
        }
        
        /// <remarks/>
        public int Eggs {
            get {
                return this.eggsField;
            }
            set {
                this.eggsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Artiodactyls))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Mammal : Animal {
        
        private TypeCover coverField;
        
        private double temperatureField;
        
        private bool isSwimmingField;
        
        /// <remarks/>
        public TypeCover Cover {
            get {
                return this.coverField;
            }
            set {
                this.coverField = value;
            }
        }
        
        /// <remarks/>
        public double Temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSwimming {
            get {
                return this.isSwimmingField;
            }
            set {
                this.isSwimmingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TypeCover {
        
        /// <remarks/>
        Spines,
        
        /// <remarks/>
        Wool,
        
        /// <remarks/>
        Shell,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Artiodactyls : Mammal {
        
        private bool isRumField;
        
        private int hoofsField;
        
        private bool hornAvailableField;
        
        private int hornLengthField;
        
        /// <remarks/>
        public bool IsRum {
            get {
                return this.isRumField;
            }
            set {
                this.isRumField = value;
            }
        }
        
        /// <remarks/>
        public int Hoofs {
            get {
                return this.hoofsField;
            }
            set {
                this.hoofsField = value;
            }
        }
        
        /// <remarks/>
        public bool HornAvailable {
            get {
                return this.hornAvailableField;
            }
            set {
                this.hornAvailableField = value;
            }
        }
        
        /// <remarks/>
        public int HornLength {
            get {
                return this.hornLengthField;
            }
            set {
                this.hornLengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddAnimalCompletedEventHandler(object sender, AddAnimalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAnimalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAnimalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddMammalCompletedEventHandler(object sender, AddMammalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMammalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMammalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddAtriCompletedEventHandler(object sender, AddAtriCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAtriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAtriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddBirdCompletedEventHandler(object sender, AddBirdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddBirdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddBirdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAnimalsCompletedEventHandler(object sender, GetAnimalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAnimalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAnimalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Animal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Animal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetMammalsCompletedEventHandler(object sender, GetMammalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMammalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMammalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Mammal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Mammal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetArtiCompletedEventHandler(object sender, GetArtiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArtiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArtiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Artiodactyls[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Artiodactyls[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetBirdsCompletedEventHandler(object sender, GetBirdsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBirdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBirdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Bird[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Bird[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RemoveAnimalsCompletedEventHandler(object sender, RemoveAnimalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveAnimalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveAnimalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RemoveMammalsCompletedEventHandler(object sender, RemoveMammalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveMammalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveMammalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RemoveArtiCompletedEventHandler(object sender, RemoveArtiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveArtiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveArtiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RemoveBirdsCompletedEventHandler(object sender, RemoveBirdsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveBirdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveBirdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591